
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      # ${POSTGRES_PASSWORD:-SUq+xmsFg7SwoBwfCYuUFw==} 使用环境变量POSTGRES_PASSWORD或者默认密码
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SUq+xmsFg7SwoBwfCYuUFw==}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.4.1
    container_name: redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD:-SUq+xmsFg7SwoBwfCYuUFw==}" ]
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-SUq+xmsFg7SwoBwfCYuUFw==}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge