name: Docker Build and Push on Tag

on:
  push:
    tags:
      - "v*" # 匹配以 v 开头的标签，如 v1.0.0, v2.1.3

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            ## Changelog
            - Docker image built and pushed to GitHub Packages
            - Image tags: 
              - ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
              - ghcr.io/${{ github.repository }}:latest
